---
Name: cacheable_navigation_config
After:
  - 'framework/*'
  - 'cms/*'
---
Director:
  rules:
    cacheable/inspector: CacheableCacheInspectorController
---
Only:
  Environment: 'dev'
---
Injector:
  MySQLDatabase:
    class: MySQLDebuggableDatabase